import { PortfolioData } from '../models/portfolio.model';

export const DEFAULT_PORTFOLIO_DATA: PortfolioData = {
  themePreset: 'dark',
  colors: {
    primary: '#6366f1',
    secondary: '#818cf8',
    accent: '#f43f5e',
    background: '#0f172a',
    sectionBg: '#1e293b',
    text: '#94a3b8',
    heading: '#f8fafc',
    link: '#818cf8',
    button: '#6366f1',
    buttonHover: '#4f46e5',
    cardBg: '#1e293b',
    borderColor: '#334155',
    footerBg: '#090d16',
    headerBg: '#0f172a',
    navbarBg: 'rgba(15, 23, 42, 0.85)',
    selectionColor: 'rgba(99, 102, 241, 0.2)',
  },
  typography: {
    fontFamily: 'Inter',
    headingSize: 'xl',
    paragraphSize: 'md',
    lineHeight: 'relaxed',
    letterSpacing: 'normal',
    fontWeight: 'medium',
  },
  layout: {
    containerWidth: 'max-w-6xl',
    padding: 'normal',
    borderRadius: 'lg',
    shadow: 'md',
    sectionSpacing: 'md',
    animation: 'fade',
    animationsEnabled: true,
  },
  navbar: {
    visible: true,
    logoText: 'Alex.dev',
    isSticky: true,
    isTransparent: true,
    hasShadow: true,
    menuColor: '#94a3b8',
    activeColor: '#6366f1',
    hoverColor: '#f8fafc',
    links: [
      { label: 'About', sectionId: 'about', visible: true },
      { label: 'Skills', sectionId: 'skills', visible: true },
      { label: 'Experience', sectionId: 'experience', visible: true },
      { label: 'Projects', sectionId: 'projects', visible: true },
      { label: 'Education', sectionId: 'education', visible: true },
      { label: 'Certifications', sectionId: 'certifications', visible: true },
      { label: 'Achievements', sectionId: 'achievements', visible: true },
      { label: 'Contact', sectionId: 'contact', visible: true },
    ],
  },
  hero: {
    id: 'hero',
    visible: true,
    name: 'Alex Rivera',
    role: 'Senior Full Stack Software Architect',
    description:
      'Crafting high-performance web applications, scalable cloud microservices, and sleek user interfaces with modern web technologies.',
    profileImage:
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    imageShape: 'rounded',
    imageBorder: true,
    imageShadow: true,
    imageOpacity: 1,
    ctaPrimaryLabel: 'Resume',
    ctaPrimaryUrl: 'assets/resume.pdf',
    resumeUrl: '',
    resumeFileName: '',
    ctaSecondaryLabel: 'Get In Touch',
    ctaSecondaryUrl: '#contact',
    socialLinks: [
      { platform: 'GitHub', url: 'https://github.com', icon: 'github' },
      { platform: 'LinkedIn', url: 'https://linkedin.com', icon: 'linkedin' },
      { platform: 'Twitter', url: 'https://twitter.com', icon: 'twitter' },
      { platform: 'Email', url: 'mailto:alex.rivera@example.com', icon: 'mail' },
    ],
    bgType: 'solid',
    bgGradientFrom: '#4f46e5',
    bgGradientTo: '#ec4899',
    height: 'screen',
    alignment: 'left',
  },
  about: {
    id: 'about',
    visible: true,
    title: 'About Me',
    subtitle: 'Passionate about engineering elegant solutions for complex digital challenges',
    description:
      'With over 8 years of hands-on experience in full-stack web software engineering, I specialize in building reactive frontend web apps in Angular & React, resilient node services, and cloud architecture. I focus on clean code, performance, accessibility, and intuitive UI design.',
    highlights: [
      'Architected cloud applications serving over 2M+ active monthly users.',
      'Pioneered design systems that boosted engineering team velocity by 40%.',
      'Strong proponent of open source software, micro-frontends, and automated CI/CD pipelines.',
    ],
    image: '',
    personalDetails: {
      fullName: 'Alex Rivera',
      currentRole: 'Senior Full Stack Architect',
      age: '28 Years',
      location: 'San Francisco, CA',
      nationality: 'American',
      email: 'alex.rivera@example.com',
      phone: '+1 (555) 234-5678',
      languages: 'English, Spanish',
      freelanceStatus: 'Available for Hire',
    },
    customDetails: [
      { id: '1', label: 'Full Name', value: 'Alex Rivera' },
      { id: '2', label: 'Current Role', value: 'Senior Full Stack Architect' },
      { id: '3', label: 'Location', value: 'San Francisco, CA' },
      { id: '4', label: 'Age / DOB', value: '28 Years' },
      { id: '5', label: 'Nationality', value: 'American' },
      { id: '6', label: 'Languages', value: 'English, Spanish' },
      { id: '7', label: 'Email Address', value: 'alex.rivera@example.com' },
      { id: '8', label: 'Phone Number', value: '+1 (555) 234-5678' },
      { id: '9', label: 'Freelance Status', value: 'Available for Hire' },
    ],
    experienceYears: '8+',
    projectsCount: '45+',
    clientsCount: '20+',
  },
  skills: {
    id: 'skills',
    visible: true,
    title: 'Core Technical Expertise',
    subtitle: 'Technologies and tools I work with to bring digital products to life',
    skills: [
      { id: '1', name: 'Angular & RxJS', percentage: 95, category: 'Frontend', icon: 'code', color: '#6366f1' },
      { id: '2', name: 'TypeScript & JavaScript', percentage: 92, category: 'Languages', icon: 'code', color: '#818cf8' },
      { id: '3', name: 'Tailwind CSS & SCSS', percentage: 90, category: 'Styling', icon: 'code', color: '#38bdf8' },
      { id: '4', name: 'Node.js & Express / NestJS', percentage: 88, category: 'Backend', icon: 'code', color: '#10b981' },
      { id: '5', name: 'REST APIs & GraphQL', percentage: 85, category: 'APIs', icon: 'code', color: '#f59e0b' },
      { id: '6', name: 'Docker & Kubernetes', percentage: 80, category: 'DevOps', icon: 'code', color: '#ec4899' },
      { id: '7', name: 'PostgreSQL & MongoDB', percentage: 82, category: 'Database', icon: 'color', color: '#a855f7' },
      { id: '8', name: 'Jest & Playwright E2E', percentage: 86, category: 'Testing', icon: 'code', color: '#06b6d4' },
    ],
  },
  experience: {
    id: 'experience',
    visible: true,
    title: 'Professional Experience',
    subtitle: 'My journey through tech companies and high-impact engineering teams',
    experiences: [
      {
        id: '1',
        company: 'Apex Tech Solutions',
        role: 'Lead Frontend Architect',
        duration: '2023 - Present',
        location: 'San Francisco, CA',
        description:
          'Directing frontend architecture for enterprise analytics dashboards. Migration of legacy Angular modules to Standalone components & Signals resulting in 35% faster initial page load.',
        logo: '',
        technologies: ['Angular 20', 'Signals', 'RxJS', 'TailwindCSS', 'Micro-frontends'],
      },
      {
        id: '2',
        company: 'CloudScale Innovations',
        role: 'Senior Full Stack Engineer',
        duration: '2020 - 2023',
        location: 'Remote',
        description:
          'Engineered real-time data streaming pipelines and responsive user interfaces for cloud management platforms. Mentored junior engineers and led sprint planning.',
        logo: '',
        technologies: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'Docker'],
      },
      {
        id: '3',
        company: 'Nexus Software Labs',
        role: 'Frontend Web Developer',
        duration: '2017 - 2020',
        location: 'Austin, TX',
        description:
          'Built accessible component libraries and single-page applications for Fintech clients. Implemented rigorous automated unit test suites.',
        logo: '',
        technologies: ['AngularJS', 'JavaScript (ES6+)', 'Sass', 'Webpack', 'Jest'],
      },
    ],
  },
  projects: {
    id: 'projects',
    visible: true,
    title: 'Featured Projects',
    subtitle: 'A selection of open-source projects, web apps, and digital experiences I have created',
    projects: [
      {
        id: '1',
        title: 'Canvas AI Studio',
        description:
          'A web-based graphic editor built with Angular and Canvas API featuring real-time layer management and export capabilities.',
        image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80',
        githubUrl: 'https://github.com',
        liveDemoUrl: 'https://example.com',
        tags: ['Angular', 'Canvas API', 'TailwindCSS'],
        featured: true,
      },
      {
        id: '2',
        title: 'DevPulse Dashboard',
        description:
          'Real-time analytics dashboard monitoring server health, microservice latency, and API throughput with interactive charts.',
        image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80',
        githubUrl: 'https://github.com',
        liveDemoUrl: 'https://example.com',
        tags: ['TypeScript', 'Node.js', 'Chart.js'],
        featured: true,
      },
      {
        id: '3',
        title: 'Nexus Commerce Engine',
        description:
          'Headless e-commerce frontend integrated with Stripe payment APIs and dynamic cart management.',
        image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80',
        githubUrl: 'https://github.com',
        liveDemoUrl: 'https://example.com',
        tags: ['Angular', 'RxJS', 'Stripe API'],
        featured: true,
      },
    ],
  },
  education: {
    id: 'education',
    visible: true,
    title: 'Education',
    subtitle: 'Academic background and degree credentials',
    items: [
      {
        id: '1',
        degree: 'B.S. in Computer Science',
        college: 'University of California, Berkeley',
        duration: '2013 - 2017',
        grade: '3.8 GPA (Magna Cum Laude)',
        description: '',
      },
      {
        id: '2',
        degree: 'B.S. in Computer Science',
        college: 'University Name',
        duration: '2019 - 2023',
        grade: '3.8 GPA',
        description: '',
      },
    ],
  },
  certifications: {
    id: 'certifications',
    visible: true,
    title: 'Certifications & Credentials',
    subtitle: 'Verified professional industry certifications and cloud credentials',
    certifications: [
      {
        id: '1',
        title: 'AWS Certified Solutions Architect - Associate',
        issuer: 'Amazon Web Services',
        issueDate: '2022',
        credentialId: 'AWS-ASA-99420',
        credentialUrl: 'https://aws.amazon.com/verification',
        description: 'Certified expertise in cloud infrastructure design, security compliance, and cost optimization.',
        icon: 'award',
      },
      {
        id: '2',
        title: 'Google Cloud Professional Cloud Architect',
        issuer: 'Google Cloud',
        issueDate: '2023',
        credentialId: 'GCP-PCA-88310',
        credentialUrl: 'https://cloud.google.com/certification',
        description: 'Professional validation of enterprise cloud solution design and migration strategies.',
        icon: 'award',
      },
    ],
  },
  achievements: {
    id: 'achievements',
    visible: true,
    title: 'Honors & Achievements',
    subtitle: 'Recognition and awards for engineering excellence and innovation',
    achievements: [
      {
        id: '1',
        title: 'Best Engineering Innovation Award',
        issuer: 'Apex Tech Hackathon',
        year: '2023',
        description: 'Awarded 1st place among 40+ engineering teams for building an AI-powered code refactoring assistant.',
        icon: 'trophy',
      },
      {
        id: '2',
        title: 'Open Source Contributor of the Year',
        issuer: 'Global Web Community',
        year: '2022',
        description: 'Recognized for core maintenance and contributions to popular frontend utility libraries.',
        icon: 'trophy',
      },
    ],
  },
  testimonials: {
    id: 'testimonials',
    visible: true,
    title: 'Client & Peer Endorsements',
    subtitle: 'What colleagues and project managers say about working with me',
    testimonials: [
      {
        id: '1',
        name: 'Sarah Jenkins',
        role: 'VP of Product',
        company: 'Apex Tech',
        avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
        content:
          'Alex is a phenomenal software architect. His ability to translate complex business requirements into sleek, reactive frontend interfaces is unmatched.',
        rating: 5,
      },
      {
        id: '2',
        name: 'Marcus Vance',
        role: 'Engineering Director',
        company: 'CloudScale',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
        content:
          'Working alongside Alex elevated our entire team. His deep knowledge of Angular and modern web performance best practices transformed our product velocity.',
        rating: 5,
      },
    ],
  },
  contact: {
    id: 'contact',
    visible: true,
    title: 'Get In Touch',
    subtitle: 'Have a project in mind or interested in collaborating? Reach out anytime!',
    phone: '+1 (555) 234-5678',
    email: 'alex.rivera@example.com',
    address: 'San Francisco, California, USA',
    website: 'https://alexrivera.dev',
    mapEmbedUrl: '',
    socialLinks: [
      { platform: 'GitHub', url: 'https://github.com', icon: 'github' },
      { platform: 'LinkedIn', url: 'https://linkedin.com', icon: 'linkedin' },
      { platform: 'Twitter', url: 'https://twitter.com', icon: 'twitter' },
    ],
  },
  footer: {
    id: 'footer',
    visible: true,
    copyrightText: '© 2026 Alex Rivera. Built with Portfolio Builder by Gangadhar.',
    showSocialIcons: true,
    bgColor: '#090d16',
    textColor: '#94a3b8',
  },
  sectionOrder: [
    'hero',
    'about',
    'skills',
    'experience',
    'projects',
    'education',
    'certifications',
    'achievements',
    'testimonials',
    'contact',
  ],
};
